### ISSUE TITLE
Add option to ignore class methods and properties.

### ISSUE THREAD

**Issue by proofit404** [gforcada/flake8-builtins#44]
Hi, thank you for the awesome plugin!

It's helpful for me to identify if I shadow built-in function in the global or local scope.

But class methods and class attributes are somewhat different from that. Class methods do not hide anything from the global or local scope since we should refer to `self` before.

There are even situations where we are forced to write code like that. For example, Django management commands require a `help` class attribute. Django REST Framework requires `list` method on APIViews and ViewSets.

I don't want to lose the ability to find the redefinition of `int` in these files. I don't want to white `noqa` on each line with class attributes neither.

It would be helpful to be able to turn off that particular behavior.

What do you think?

Have a good day! :tada: 

Best regards, 
Artem.

**Comment by gforcada** [comment]
Hi! :wave: thanks for using **AND** reporting issues regarding this flake8 plugin!

If I'm not mistaken, since version `1.3.0` there is an error code (`A003`) that targets only class attributes. Adding that code to the list of ignored codes would be enough.

For class methods though, you are right, there is no specific error code for it.

Would you be willing to prepare a pull request that adds a new error code (`A004`?) and the logic to check for class methods? :thinking: Otherwise I can try my best to do that, but it might take some time :sweat: 

Friendly pings and reminders, are always welcome :wink:

**Comment by proofit404** [comment]
Hi, 

`A003` covers both cases. Unfortunately, I was able to understand that only from the source code.

Thanks for your explanation and the hints you gave me.

I wish you an incredible weekend :tropical_drink: 

Best regards,
Artem.
